openapi: 3.0.3
info:
  version: 1.0.0
  title: APISuite Billing Extension
  description: APISuite Billing Extension REST API
  license:
    name: MPL-2.0
paths:
  /health:
    get:
      tags: [ system ]
      summary: Healthcheck endpoint
      description: >
        Checks the general health status of the app servers.
        This usually means verifying connectivity to external dependencies.
      responses:
        '200':
          description: Healthcheck result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
        '500':
          $ref: '#/components/responses/Internal'
  /metrics:
    get:
      tags: [ system ]
      summary: System metrics for Prometheus scraping
      responses:
        '200':
          description: Prometheus metrics
          content:
            text/plain:
              schema:
                type: string
  /plans:
    get:
      tags: [ plans ]
      description: List plans. Plans without periodicity are one time top ups.
      security:
        - cookieAuth: [ ]
      responses:
        '200':
          description: Plan model list
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Plan'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
    post:
      tags: [ plans ]
      description: Create a plan
      security:
        - cookieAuth: [ ]
      responses:
        '201':
          description: Plan model
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Plan'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
  /plans/{id}:
    get:
      tags: [ plans ]
      description: Show a plan by id.
      security:
        - cookieAuth: [ ]
      parameters:
        - name: id
          in: path
          description: Plan ID
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Plan model
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Plan'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags: [ plans ]
      description: Update a plan.
      security:
        - cookieAuth: [ ]
      parameters:
        - name: id
          in: path
          description: Plan ID
          required: true
          schema:
            type: number
      requestBody:
        description: New role data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                credits:
                  type: number
                periodicity:
                  type: string
      responses:
        '200':
          description: Plan model
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Plan'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags: [ plans ]
      description: Delete a plan.
      security:
        - cookieAuth: [ ]
      parameters:
        - name: id
          in: path
          description: Plan ID
          required: true
          schema:
            type: number
      responses:
        '204':
          description: No content
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /users/{id}:
    get:
      tags: [ users ]
      description: >
        Returns a user based on the ID.
        This also sets up the user if it doesn't exist yet in the extension's context.
      security:
        - cookieAuth: [ ]
      parameters:
        - name: id
          in: path
          description: ID of user to fetch
          required: true
          schema:
            type: number
      responses:
        '200':
          description: User model
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /users/{id}/consent:
    post:
      tags: [ users ]
      description: >
        Creates an associated customer in the payment processor.
        Creates a first time payment for consent purposes.
      security:
        - cookieAuth: [ ]
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: number
      responses:
        '302':
          description: Payment processor checkout page redirect
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
  /users/{id}/plans/{planId}:
    delete:
      tags: [ users ]
      description: Cancels a subscription plan
      security:
        - cookieAuth: [ ]
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: number
        - name: id
          in: path
          description: Plan ID
          required: true
          schema:
            type: number
      responses:
        '204':
          description: No content
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /purchases:
    post:
      tags: [ purchases ]
      description: Purchase a plan, which can be a one time credit top up or a subscription.
      security:
        - cookieAuth: [ ]
      requestBody:
        description: Purchase data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plan_id:
                  type: number
      responses:
        '302':
          description: Payment processor checkout page redirect
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        picture:
          type: string
    Plan:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        price:
          type: number
        credits:
          type: number
        periodicity:
          type: string
    Health:
      type: object
      properties:
        status:
          type: string
        time:
          type: string
          format: date-time
    Error:
      type: object
      properties:
        error:
          type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Internal:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token
