version: 2.1

orbs:
  slack: circleci/slack@4.4.2

jobs:
  test:
    docker:
      - image: cimg/node:14.16
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - slack/notify:
          event: fail
          template: basic_fail_1
      - run: cp -r ../.ssh/ .
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  release:
    docker:
      - image: cimg/node:14.16
    steps:
      - attach_workspace:
          at: ~/
      - run: ./.scripts/get_version.sh .orig_version
      - run: cp -r .ssh ../.ssh && rm -rf .ssh
      - run: GH_TOKEN=$GH_TOKEN npx semantic-release
      - run: ./.scripts/get_version.sh .new_version
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - run: ./.scripts/build.sh
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  version: 2
  build:
    jobs:
      - test:
          context: slack
      - release:
          context: docker
          filters:
            branches:
              only:
                - main
          requires:
            - test
      - build:
          context:
            - docker
            - slack
          filters:
            branches:
              only:
                - main
          requires:
            - release
